channels:
  - udst
  - defaults
  - conda-forge
dependencies:
  - geopandas>=0.6.1
  - numpy>=1.17
  - pandas>=0.25.2
  - pip>=19.3.1
  - python>=3.7.4
  - requests>=2.22
  - rtree>=0.8
  - seaborn>=0.9.0
  - setuptools>=41.4
  - shapely>=1.6.4
  - wheel>=0.33.6
  - pip:
    - descartes>=1.1
    - matplotlib>=3.1
    - networkx>=2.4
    - osmnx>=0.10
    - pysal>=2.1.0
    - python-louvain>=0.13
    - twine>=3.0.0

